### ISSUE TITLE
does not working with gnome gnome 3.32

### ISSUE THREAD

**Issue by taurthil** [ivoarch/gnome-shell-TilixDropdown#18]
The extension show popup **Couldn't start tilix, is it installed**?

**Comment by busser** [comment]
I can confirm this is an issue.

The error message seems to come from the [`_startTilix`](https://github.com/ivoarch/gnome-shell-TilixDropdown/blob/cf7f4604bba76cb974d780e20f8ed944b0c77847/extension.js#L41) function.

Running the `env GDK_BACKEND=x11 tilix --quake` command directly from a terminal or in GNOME has the expected behavior: toggling a Tilix window in Quake mode.

I guess the problem is that `_startTilix`'s call to `imports.ui.main.Util.trySpawnCommandLine` throws an exception only in GNOME 3.32. Further debugging could shed light on what the exception in question is.

In the meantime, it is possible to use native GNOME configuration options to replicate the Tilix Dropdown extension's behavior:

1. Open GNOME Settings.
2. Go to Devices > Keyboard.
3. Scroll down and click on `+`.
4. Give the new shortcut a name (e.g. `Tilix Quake`).
5. As a command, write `env GDK_BACKEND=x11 tilix --quake`.
6. Click on `Set Shortcut` and set whatever key binding you want (e.g. `F10`).
    > If you want to use the same key binding as the Tilix Dropdown extension, you need to uninstall the extension or configure it to use another keybinding.
7. Click on `Add`.

I don't know if the extension adds additional behavior that cannot be replicated only with GNOME configuration. If it does, then it would be nice if the code was patched to manage GNOME 3.32's apparently new behavior.

**Comment by taurthil** [comment]
I prepare Pull Request [#19](https://github.com/ivoarch/gnome-shell-TilixDropdown/pull/19) problem is in ` Main.Util.`
